framework: jest
postMerge: 
  pattern: 
    - "**/*.test.js"
postRun: 
  command: 
    - "cd website && node --version"  
preMerge: 
  pattern: 
    - "**/*.test.js"
preRun: 
  command: 
    - cd website && npm install
configFile: jest.config.json
